version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "examples/pure-hatch/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
