# Book settings
title: The pyOpenSci Developer Guide
author: The pyOpenSci Community
logo: images/logo/logo.png
exclude_patterns: ["README.md"]

repository:
  url: https://github.com/pyOpenSci/contributing-guide
  branch: main

html:
  favicon: images/logo/logo.png
  google_analytics_id: UA-141260825-1
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  announcement: "<div class='header__block'>ATTENTION
                <p>
                We are currently updating this book to stay tuned! 
                The content should become more stable in early 2023.
                </p>
                </div>
                "
