project_id: 785976
api_token: "${{ secrets.CROWDIN_PERSONAL_TOKEN }}"
files:
  - source: /locales/en/LC_MESSAGES/messages.po
    translation: /locales/%two_letters_code%/LC_MESSAGES/messages.po
    type: gettext
